# fly.toml app configuration file generated for movie-graph on 2025-01-22T21:18:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movie-graph'
primary_region = 'lhr'

[build]
  image = 'neo4j:5.26.1-community-bullseye'

[deploy]
  strategy = 'immediate'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1gb'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1gb'
  auto_extend_size_limit = '10gb'

[http_service]
  internal_port = 7474
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
