---
name: Convert IMDb data to a graph
on: push

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --dev
      - name: Run linter
        run: uv run black --check --diff src/movie-graph
  convert:
    name: Download and convert to Neo4j
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync
      - name: Run imdb-sqlite
        run: uv run imdb-sqlite
      - name: Run converter
        env:
          NEO4J_URI: bolt://localhost:7687
          NEO4J_USER: neo4j
          NEO4J_PASSWORD: test
        run: uv run -m src.convert imdb.db
